name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6673367574cbd913d9ec2cc640b885636710cc34206d075f5ff385297662adf4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
