name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dd19cfa2542b6f3ce6544c851dbff20cb37a1326d273e9e3efeb28d70ac71d0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
