name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2878168739d504072153f175381b2932f821a212ae3c1baed37f2b028ca1490e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
