name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec11821b604bbb5f8a3702eb6ad16e4a265c3a082d346429c2897c76bb82fc8c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
