name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c212461c3bde05c5732ff92149ec13d8432b96cd58ae0070959ebb6c68121f9"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
