name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8064c7c3a8fde643917d28aea2b6eba83b57d0e5cf1347a70e8eb2399ba22160"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
