name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ce68d8961fcbd46884cab659a205177e13c7cc092a944a2c9268eeca3ec7248"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
