name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32f9513a28134125521bd10144b28efbce70e9d018ca0d9d4bbd49a5a78bfc99"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
