name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40f7b7a35986c36e5348ce209c42cc5c2c74f3d8f267e88af05e82910ec08202"

[versions]
fabric = "0.14.23"
forge = "52.1.0"
minecraft = "1.20.1"
