name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bea171f625c2ab7bd16bc9646bd8df5af4b1dfbd8c3c4e9b049bfc5f6580c982"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
