name = "Craft Nectar Modpack"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d587e468904126b3b5c46f747ea7eeb27f6d916565e3157ee50e6a5d99773803"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
